docs: add ecs README.md
TEAM-AAAAAAAAAAAAAAAA/RTYPE pull request #55
Opened 2022-10-12 16:16 UTC by Bootoyka

Fix: #51.

2022-10-12 16:35 UTC, Cavonstavant approved these changes
YES !

2022-10-12 21:06 UTC, Cavonstavant approved these changes
Ok, grammar and syntax needs to be fixed otherwise it's a good start. This will be enough for now

2022-10-13 07:47 UTC, GuyomT approved these changes
Trusting @EmileEttel for correction
NTR

2022-10-13 07:56 UTC, EmileEttel requested changes
Few typos and some personal gripes with phrasing, but some of the suggestions are personal

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +In the same way, the component store a self delete methods as a lambda in a `_earase_func` private vector.
```suggestion
In the same way, the component stores a self delete methods as a lambda in a `_eraseFunc` private vector.
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +Systems are the thing who directly interacts with components.
```suggestion
Systems are the things that directly interacts with components.
```
Systems are not people, don't use who

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +They actually get all the associated components in oder to actualize Entities values.
```suggestion
They actually get all the associated components in order to actualize Entities' values.
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +They are generated in lambda forma and pushed in the private vector of the current world.
```suggestion
They are generated in lambda format and pushed in the private vector of the current world.
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +This function is not used by the developper but it allows, in back end, to allow a new type of components in the registry.
```suggestion
This function is not used by the developper but it allows, in back end, a new type of components in the registry.
```

it allows to allow, are you sure that's what it does
(I don't) Up to you

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +This is the most interessant part if we speak about managing components because it's the **Components Manager** by definition.
```suggestion
This is the most interesting part if we talk about managing components because it's the **Components Manager** by definition.
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +Let's just define what a world is before giving you a good example of adding a component and make it run properly.
```suggestion
Let's just define what a world is before giving you a good example of adding a component and making it run properly.
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +Let's just define what a world is before giving you a good example of adding a component and make it run properly.
Not sure tbh about this change, up to you

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +In this way, world contain every usefull component & system which is associated with it.
```suggestion
In this way, world contains every useful component & system which is associated with it.
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +As example we'll not use component Position or Velocity in the server world.
```suggestion
For example, we'll not use component Position or Velocity in the server world.
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +Lets now decompose our main function who's actually creating a world, spawn two entities and gives the player the possibility to move  and shoot :
```suggestion
Now let's decompose our main function who's actually creating a world, spawn two entities and gives the player the possibility to move  and shoot :
```

2022-10-13 07:56 UTC, EmileEttel commented on src/ecs/README.md
> +Lets now decompose our main function who's actually creating a world, spawn two entities and gives the player the possibility to move  and shoot :
Up to you

2022-10-13 11:37 UTC, aurelenc approved these changes

2022-10-13 11:57 UTC, Bootoyka commented
> Few typos and some personal gripes with phrasing, but some of the suggestions are personal

i trust you 100%

2022-10-13 11:58 UTC, EmileEttel approved these changes
LGTM

2022-10-13 11:59 UTC, merged