Music asset manager
TEAM-AAAAAAAAAAAAAAAA/RTYPE pull request #86
Opened 2022-11-07 01:13 UTC by Cavonstavant

# This pull request adds audio support to the projet.

## Misc modifications
- `AssetLoader`  was updated to allow multiple assets type mgmt
    - currently loading: `textures`, `audio` and `fonts`
- All assets are loaded inside the `AssetLoader` and can be accessed by using the associated getter type

## New features
A new class `audio::AudioManager` implements two ways of interracting with audio within the project.
Audio is managed in two ways. Buffered and non-buffered.
### Buffered
This type is proper to use with small, short audio files like sound effects. It loads the file into memory using an `sf::SoundBuffer` and can be played with latency.
This type is refered to a SFX all along the code

### Non-buffered
This type is proper to use with large, long audio files like background music. It uses an `sf::Music` that is based on an `sf::SoundStream`.
> Unlike audio buffers (see [sf::SoundBuffer](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1SoundBuffer.php)), > audio streams are never completely loaded in memory.
> Instead, the audio data is acquired continuously while the stream is playing. This behavior allows to play a sound with no loading delay, and keeps the memory consumption very low.
This type is refered to a BGM all along the code

2022-11-08 10:43 UTC, aurelenc requested changes
- Replace tabs by 4 spaces
- Remove copyrighted songs

2022-11-08 13:41 UTC, GuyomT approved these changes
not building but code is clear

LGTM

2022-11-08 14:53 UTC, Bootoyka approved these changes
Still looking for the correlation between the pull request's name and the content but lgtm

2022-11-08 14:53 UTC, Bootoyka commented on .gdb_history
>  q
Please ensure that you don't push .gdb_history

2022-11-09 17:40 UTC, aurelenc approved these changes

2022-11-09 17:44 UTC, merged